export const SET_CAMPS = "SET_CAMPS";
export const REMOVE_CAMP = "REMOVE_CAMP";
export const CAMP_ADDED = "CAMP_ADDED";
export const START_ADD_CAMP = "START_ADD_CAMP";

export const REGISTRATION_UPDATE = "REGISTRATION_UPDATE";
export const REGISTRATION_CREATE = "REGISTRATION_CREATE";
export const REGISTRATION_SAVE_SUCCESS = "REGISTRATION_SAVE_SUCCESS";

export const REGISTRATIONHISTORY_UPDATE = "REGISTRATIONHISTORY_UPDATE";
export const REGISTRATIONHISTORY_CREATE = "REGISTRATIONHISTORY_CREATE";
export const REGISTRATIONHISTORY_SAVE_SUCCESS = "REGISTRATIONHISTORY_SAVE_SUCCESS";

export const EMPLOYMENT_UPDATE = "EMPLOYMENT_UPDATE";
export const EMPLOYMENT_CREATE = "EMPLOYMENT_CREATE";
export const EMPLOYMENT_SAVE_SUCCESS = "EMPLOYMENT_SAVE_SUCCESS";

export const SPECIALNEED_UPDATE = "SPECIALNEED_UPDATE";
export const SPECIALNEED_CREATE = "SPECIALNEED_CREATE";
export const SPECIALNEED_SAVE_SUCCESS = "SPECIALNEED_SAVE_SUCCESS";

export const SET_FAMILYCOUNT = "SET_FAMILYCOUNT";
export const SET_CURRENTCOUNT = "SET_CURRENTCOUNT";

export const TRY_AUTH = "TRY_AUTH";

export const UI_START_LOADING = "UI_START_LOADING";
export const UI_STOP_LOADING = "UI_STOP_LOADING";

export const AUTH_SET_TOKEN = "AUTH_SET_TOKEN";
export const AUTH_REMOVE_TOKEN = "AUTH_REMOVE_TOKEN";
